/**
 * XRPL Impact Fund - Shared Type Definitions
 *
 * This file contains all type definitions shared between:
 * - Backend API
 * - Frontend Application
 * - AI Trading Engine
 *
 * Import this file in both backend and frontend for type consistency.
 */

// ============================================================================
// CORE DOMAIN TYPES
// ============================================================================

/**
 * Represents a donor in the XRPL Impact Fund
 */
export interface DonorInfo {
  /** XRPL wallet address */
  address: string;

  /** Total amount donated in XRP */
  totalDonated: number;

  /** Experience points (1 XRP = 10 XP) */
  xp: number;

  /** Calculated level: floor(sqrt(xp/100)) + 1 */
  level: number;

  /** NFT token ID if minted */
  nftTokenId?: string;

  /** Donor Impact Token (DIT) ID for governance */
  ditTokenId?: string;

  /** First donation timestamp */
  firstDonationDate: Date;

  /** Most recent donation timestamp */
  lastDonationDate: Date;

  /** Total number of donations made */
  donationCount: number;
}

/**
 * Represents an NGO in the system
 */
export interface NGO {
  /** Unique identifier */
  id: string;

  /** Display name */
  name: string;

  /** XRPL wallet address for receiving funds */
  walletAddress: string;

  /** Primary focus area */
  category: 'climate' | 'health' | 'education' | 'water' | 'other';

  /** Impact Oracle score (0-100) */
  impactScore: number;

  /** Distribution weight (0-1, sum of all weights = 1) */
  weight: number;

  /** Total XRP received from distributions */
  totalReceived: number;

  /** Whether NGO has been validated by Impact Oracle */
  verified: boolean;

  /** List of certifications (UN, OECD, etc.) */
  certifications: string[];

  /** NGO website URL */
  website?: string;

  /** Brief description of mission */
  description?: string;

  /** Registration timestamp */
  createdAt: Date;

  /** Last update timestamp */
  updatedAt: Date;
}

/**
 * Represents the current state of the donation pool
 */
export interface PoolState {
  /** Current total balance in XRP */
  totalBalance: number;

  /** Total XRP donated by all donors */
  totalDonations: number;

  /** Total profits generated by AI trading */
  totalProfitsGenerated: number;

  /** Total XRP distributed to NGOs */
  totalDistributed: number;

  /** Last time AI trading was executed */
  lastTradingRun: Date | null;

  /** Number of unique donors */
  donorCount: number;
}

/**
 * Represents a profit distribution event to NGOs
 */
export interface DistributionRecord {
  /** Unique identifier */
  id: string;

  /** NGO recipient ID */
  ngoId: string;

  /** NGO name for display */
  ngoName: string;

  /** Amount distributed in XRP */
  amount: number;

  /** XRPL transaction hash */
  txHash: string;

  /** Distribution timestamp */
  timestamp: Date;
}

// ============================================================================
// API REQUEST/RESPONSE TYPES
// ============================================================================

/**
 * Request body for submitting a donation
 */
export interface DonationRequest {
  /** Donor's XRPL wallet address */
  donorAddress: string;

  /** Amount to donate in XRP */
  amount: number;

  /** Optional transaction signature for verification */
  signature?: string;
}

/**
 * Response after successful donation
 */
export interface DonationResponse {
  /** Updated donor information */
  donor: DonorInfo;

  /** NFT minting result (if applicable) */
  nft?: NFTMintResult;

  /** DIT token result (if first donation) */
  dit?: DITMintResult;

  /** Updated pool state */
  poolState: PoolState;
}

/**
 * Result of AI trading profit simulation
 */
export interface SimulationResult {
  /** Profit amount in XRP */
  profitAmount: number;

  /** Profit as percentage of pool balance */
  profitPercentage: number;

  /** New pool balance after profit */
  newBalance: number;

  /** Trading signal that generated profit */
  signal: 'BUY' | 'SELL' | 'HOLD';

  /** Confidence level of signal (0-1) */
  confidence: number;

  /** Optional detailed trading metrics */
  tradingMetrics?: TradingMetrics;
}

/**
 * Request for NGO validation
 */
export interface NGOValidationRequest {
  /** NGO ID to validate */
  ngoId: string;

  /** Optional registration number */
  registrationNumber?: string;

  /** Optional website for verification */
  website?: string;

  /** Optional country code */
  country?: string;
}

/**
 * Result of NGO validation by Impact Oracle
 */
export interface ValidationResult {
  /** NGO ID */
  ngoId: string;

  /** Calculated impact score (0-100) */
  impactScore: number;

  /** Detailed validation checks */
  checks: {
    /** Registration verified against databases */
    registrationVerified: boolean;

    /** Financial transparency meets standards */
    financialTransparency: boolean;

    /** Impact metrics available and valid */
    impactMetrics: boolean;

    /** List of verified certifications */
    certifications: string[];

    /** Any red flags detected */
    redFlags: string[];
  };

  /** Overall validation status */
  validated: boolean;

  /** Validation timestamp */
  timestamp: Date;
}

// ============================================================================
// TRADING & AI TYPES
// ============================================================================

/**
 * Trading signal generated by AI algorithm
 */
export interface TradingSignal {
  /** Recommended action */
  action: 'BUY' | 'SELL' | 'HOLD';

  /** Confidence level (0-1) */
  confidence: number;

  /** Technical indicators used */
  indicators: {
    /** 50-period Simple Moving Average */
    sma50: number;

    /** 200-period Simple Moving Average */
    sma200: number;

    /** 14-period Relative Strength Index */
    rsi: number;
  };

  /** Signal generation timestamp */
  timestamp: Date;
}

/**
 * Performance metrics for trading algorithm
 */
export interface TradingMetrics {
  /** Total number of trades executed */
  totalTrades: number;

  /** Number of profitable trades */
  profitableTrades: number;

  /** Total profit/loss in XRP */
  totalProfit: number;

  /** Return on Investment percentage */
  roi: number;

  /** Risk-adjusted return metric */
  sharpeRatio: number;

  /** Maximum drawdown percentage */
  maxDrawdown: number;
}

/**
 * Market candlestick data for AI algorithm
 */
export interface MarketCandle {
  /** Candle timestamp (Unix milliseconds) */
  timestamp: number;

  /** Opening price */
  open: number;

  /** Highest price */
  high: number;

  /** Lowest price */
  low: number;

  /** Closing price */
  close: number;

  /** Trading volume */
  volume: number;
}

// ============================================================================
// XRPL BLOCKCHAIN TYPES
// ============================================================================

/**
 * Result of XRPL payment transaction
 */
export interface TransactionResult {
  /** Transaction succeeded */
  success: boolean;

  /** XRPL transaction hash */
  txHash: string;

  /** Transaction fee in XRP */
  fee: string;

  /** Transaction timestamp */
  timestamp: string;

  /** Transaction validated on ledger */
  validated: boolean;

  /** Error message if failed */
  error?: string;
}

/**
 * Parameters for sending XRPL payment
 */
export interface PaymentParams {
  /** Sender address */
  from: string;

  /** Recipient address */
  to: string;

  /** Amount in XRP */
  amount: number;

  /** Optional memo */
  memo?: string;
}

/**
 * Result of NFT minting operation
 */
export interface NFTMintResult {
  /** Minting succeeded */
  success: boolean;

  /** NFT token identifier */
  tokenId: string;

  /** NFT metadata URI */
  uri: string;

  /** Owner's XRPL address */
  ownerAddress: string;

  /** Minting transaction hash */
  txHash: string;

  /** NFT metadata */
  metadata: NFTMetadata;
}

/**
 * NFT metadata structure
 */
export interface NFTMetadata {
  /** Donor level */
  level: number;

  /** Donor XP */
  xp: number;

  /** NFT tier based on level */
  tier: 'Bronze' | 'Silver' | 'Gold' | 'Platinum' | 'Diamond';

  /** Evolution stage (number of level-ups) */
  evolution: number;

  /** Additional custom attributes */
  attributes?: Record<string, any>;
}

/**
 * Parameters for minting NFT
 */
export interface NFTMintParams {
  /** Donor address (NFT recipient) */
  donorAddress: string;

  /** NFT metadata URI */
  uri: string;

  /** NFT metadata */
  metadata: NFTMetadata;

  /** Whether NFT is transferable */
  transferable?: boolean;
}

/**
 * Donor Impact Token (DIT) minting result
 */
export interface DITMintResult {
  /** Minting succeeded */
  success: boolean;

  /** Token identifier */
  tokenId: string;

  /** Owner's address */
  ownerAddress: string;

  /** Governance voting power */
  votingPower: number;

  /** Transaction hash */
  txHash: string;
}

/**
 * Transaction verification result
 */
export interface VerificationResult {
  /** Transaction found and validated */
  validated: boolean;

  /** Transaction succeeded */
  success: boolean;

  /** Transaction timestamp */
  timestamp?: string;

  /** Transaction fee */
  fee?: string;

  /** Error message if verification failed */
  error?: string;
}

// ============================================================================
// HEALTH & STATUS TYPES
// ============================================================================

/**
 * System health check response
 */
export interface HealthStatus {
  /** Overall system status */
  status: 'healthy' | 'degraded' | 'down';

  /** XRPL network mode */
  mode: 'MOCK' | 'TESTNET' | 'MAINNET' | 'DEVNET';

  /** Individual service health */
  services: {
    /** XRPL client connection */
    xrpl: boolean;

    /** Database connection */
    database: boolean;

    /** Redis connection */
    redis: boolean;

    /** AI trading service */
    aiTrading: boolean;
  };

  /** Pool information snapshot */
  poolInfo: {
    /** Current balance */
    balance: number;

    /** Number of donors */
    donorCount: number;

    /** Number of NGOs */
    ngoCount: number;
  };

  /** Health check timestamp */
  timestamp: Date;
}

// ============================================================================
// CONFIGURATION TYPES
// ============================================================================

/**
 * XRPL client configuration
 */
export interface XRPLConfig {
  /** Network to connect to */
  network: 'mock' | 'testnet' | 'mainnet' | 'devnet';

  /** WebSocket URL for XRPL node */
  websocketUrl?: string;

  /** Pool wallet seed (for signing) */
  poolWalletSeed?: string;

  /** Pool wallet address */
  poolWalletAddress: string;

  /** Enable mock mode (no real transactions) */
  mockMode: boolean;
}

/**
 * AI trading configuration
 */
export interface AITradingConfig {
  /** Enable AI trading */
  enabled: boolean;

  /** Trading interval in hours */
  intervalHours: number;

  /** Maximum percentage of pool per trade */
  maxPositionSize: number;

  /** Risk tolerance level */
  riskTolerance: 'conservative' | 'moderate' | 'aggressive';
}

// ============================================================================
// GOVERNANCE TYPES
// ============================================================================

/**
 * Governance proposal
 */
export interface Proposal {
  /** Unique identifier */
  id: string;

  /** Proposal title */
  title: string;

  /** Detailed description */
  description: string;

  /** Proposal type */
  type: 'add_ngo' | 'remove_ngo' | 'update_weights' | 'parameter_change';

  /** Proposer address */
  proposer: string;

  /** Voting options */
  options: string[];

  /** Vote counts per option */
  votes: Record<string, number>;

  /** Total voting power cast */
  totalVotes: number;

  /** Proposal status */
  status: 'active' | 'passed' | 'rejected' | 'executed';

  /** Start timestamp */
  startDate: Date;

  /** End timestamp */
  endDate: Date;

  /** Execution timestamp (if passed) */
  executedAt?: Date;
}

/**
 * Vote on a proposal
 */
export interface Vote {
  /** Proposal ID */
  proposalId: string;

  /** Voter address */
  voterAddress: string;

  /** Selected option */
  option: string;

  /** Voting power used */
  votingPower: number;

  /** Vote timestamp */
  timestamp: Date;
}

// ============================================================================
// ANALYTICS TYPES
// ============================================================================

/**
 * Donation statistics over time
 */
export interface DonationStats {
  /** Total donations in period */
  totalAmount: number;

  /** Number of donations */
  count: number;

  /** Average donation size */
  averageAmount: number;

  /** Largest single donation */
  maxAmount: number;

  /** Smallest donation */
  minAmount: number;

  /** Period start date */
  periodStart: Date;

  /** Period end date */
  periodEnd: Date;
}

/**
 * Impact metrics for dashboard
 */
export interface ImpactMetrics {
  /** Total lives impacted (estimated) */
  livesImpacted: number;

  /** CO2 offset in tons */
  co2Offset: number;

  /** Children educated */
  childrenEducated: number;

  /** People with clean water access */
  waterAccessProvided: number;

  /** Medical treatments funded */
  medicalTreatments: number;
}

/**
 * Leaderboard entry
 */
export interface LeaderboardEntry {
  /** Rank position */
  rank: number;

  /** Donor address */
  address: string;

  /** Display name (if set) */
  displayName?: string;

  /** Total donated */
  totalDonated: number;

  /** Current XP */
  xp: number;

  /** Current level */
  level: number;

  /** NFT tier */
  tier: string;
}

// ============================================================================
// ERROR TYPES
// ============================================================================

/**
 * Standardized error response
 */
export interface ErrorResponse {
  /** Error message */
  message: string;

  /** Error code */
  code: string;

  /** HTTP status code */
  statusCode: number;

  /** Additional error details */
  details?: Record<string, any>;

  /** Error timestamp */
  timestamp: Date;
}

// ============================================================================
// UTILITY TYPES
// ============================================================================

/**
 * Paginated response wrapper
 */
export interface PaginatedResponse<T> {
  /** Data items */
  data: T[];

  /** Total number of items */
  total: number;

  /** Current page number */
  page: number;

  /** Items per page */
  pageSize: number;

  /** Total pages */
  totalPages: number;

  /** Whether there are more pages */
  hasMore: boolean;
}

/**
 * Pagination request parameters
 */
export interface PaginationParams {
  /** Page number (1-indexed) */
  page?: number;

  /** Items per page */
  pageSize?: number;

  /** Sort field */
  sortBy?: string;

  /** Sort direction */
  sortOrder?: 'asc' | 'desc';
}
